### ISSUE TITLE
404 Error on GHES repo

### ISSUE THREAD

**Issue by sirirao88** [Nef10/lcov-reporter-action#594]
Hello,

Thank you for this great action.

While I am trying to use this action in one of the GHES repo, I encounter the below issue (screenshot attached). I see that the url shows the correct GHES url but still error out with 404 Not Found.

![image](https://github.com/Nef10/lcov-reporter-action/assets/51156132/e8ffea5e-8624-4ea8-a0cb-fc227d96de7d)

Below is how I use it in the workflow .yml file:

```
- name: Upload Shell Coverage Reports
  uses: Nef10/lcov-reporter-action@v0.4.0
  env:  
    PR_NUMBER: ${{ github.event.pull_request.number }}
  with:
    lcov-file: shell/target/jscoverage/shell-lcov.info
    github-token: ${{ secrets.GITHUB_TOKEN }}
```
Is there something missing in the above snippet or is it not supported completely to be used in the GHES workflows?
Thanks you in advance for looking into the issue.
